baseURL = 'https://a8king.com/'
languageCode = 'en-us'
title = 'Health for you life'
theme = 'ananke'
sectionPagesMenu = 'main'
defaultContentLanguage = 'en'
copyright = 'Health Anythings'

[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

[params]
  # AdSense 配置
  [params.adsense]
  publisher_id = "pub-4522670236044605"
  enable_ads = true
  article_ads_only = true            # 只在文章页显示广告
  
  # 文章页广告单元ID配置
  [params.adsense.slots]
    article_title = "7397784842"      # 文章标题下广告单元ID - 需要替换为真实ID
    article_middle = "4484459277"     # 文章中间广告单元ID
    article_bottom = "2089847106"     # 文章底部广告单元ID


googleAnalytics = 'G-RLJ7MJ39WG'

[services]
  [services.googleAnalytics]
    id = 'G-RLJ7MJ39WG'
    respectDoNotTrack = true
    anonymizeIP = true



[languages]
  [languages.en]
    contentDir = 'content/english'
    languageName = 'English'
    weight = 10
  [languages.fr]
    contentDir = 'content/french'
    languageName = 'Français'
    weight = 15
  [languages.sp]
    contentDir = 'content/spanish'
    languageName = 'Spanish'
    weight = 15
  [languages.cn]
    contentDir = 'content/chinese'
    languageName = 'Chinese'
    weight = 15
  [languages.jp]
    contentDir = 'content/japanese'
    languageName = 'Japanese'
    weight = 15
